/**
 * Sets MIN_SCORE and STRONG_SCORE in src/lib/rag/attribute.ts from data.
 *
 * `npm run calibrate:attribution`
 *
 * Retrieval only — no LLM, no API key, no cost, and the same numbers every run.
 * The selections are built from the passages that actually came back rather than
 * from fixtures, so the score distribution is the one the feature will meet:
 *
 *   verbatim     a sentence lifted from the top passage unchanged
 *   reworded     the same claim, hand-rewritten (the column that decides STRONG_SCORE)
 *   synthesis    a hand-written claim that draws on two passages at once
 *   unsupported  a claim about something outside the corpus
 *
 * What this exists to show is a negative result (ADR-0024): `reworded` and
 * `synthesis` overlap, so no threshold separates a paraphrase from an assembled
 * claim, and the code must not pretend otherwise. If a future change appears to
 * separate them, this is the script that has to prove it.
 */
import { getDb } from "@/lib/db";
import { getEmbeddingBaseUrl, getEmbeddingModel, getQdrantUrl } from "@/lib/env";
import { attribute, rankPassages, type AttributionSource } from "@/lib/rag/attribute";
import { retrieve } from "@/lib/rag/retrieve";
import { splitSentences } from "@/lib/rag/sentences";
import { createClient } from "@/lib/rag/vector";

const db = getDb();
const deps = {
  qdrant: createClient(getQdrantUrl()),
  embedding: { baseUrl: getEmbeddingBaseUrl(), model: getEmbeddingModel() },
  loadChunks: async (ids: string[]) => {
    const rows = await db.chunk.findMany({ where: { id: { in: ids } }, include: { document: true } });
    return rows.map((r) => ({
      id: r.id, documentId: r.documentId, collectionId: r.collectionId, page: r.page,
      headingPath: r.headingPath, displayText: r.displayText, filename: r.document.filename,
    }));
  },
};

/**
 * The reworded and synthesis selections are hand-written, which is the point of
 * both columns: a paraphrase generated by rearranging the source text would keep
 * the source vocabulary and score far too well, and a "synthesis" built by
 * concatenating two verbatim sentences is not synthesis at all — it is a
 * verbatim match with extra words attached, and it scores like one. Both
 * mistakes were made in the first version of this script.
 */
const CASES: {
  collection: string;
  question: string;
  reworded: string;
  synthesis: string;
  unsupported: string;
}[] = [
  {
    collection: "Clinical Operations",
    question: "Who is permitted to make modifications or corrections to eCRF data?",
    reworded:
      "Changes to eCRF data may only be made by the investigator or by study staff they have delegated the task to.",
    synthesis:
      "Only delegated staff may change eCRF data, and every such change has to keep the original entry recoverable.",
    unsupported: "Sponsors must destroy all unused investigational product within thirty days.",
  },
  {
    collection: "Clinical Operations",
    question: "What specific responsibilities does an Institutional Review Board have regarding informed consent materials?",
    reworded:
      "The IRB is required to review and approve the consent documents given to prospective subjects before they are used.",
    synthesis:
      "The IRB approves the consent materials, and a copy of what was signed goes to the person giving consent.",
    unsupported: "Veterinary drug labelling must carry a withdrawal period for food-producing animals.",
  },
  {
    collection: "Clinical Operations",
    question: "What potential advantages does using electronic health records offer in clinical investigations?",
    reworded:
      "Using EHRs can give investigators access to more complete long-term patient data and cut down on manual transcription.",
    synthesis:
      "EHR data can reduce transcription work, and sponsors have to validate that the EHR and EDC systems interoperate.",
    unsupported: "Sourdough starters need a stable ambient temperature to ferment reliably.",
  },
];

const bands = new Map<string, number[]>();
const record = (kind: string, score: number) =>
  bands.set(kind, [...(bands.get(kind) ?? []), score]);

const band = (score: number) => (score >= 0.6 ? "strong" : score >= 0.35 ? "partial" : "DECLINED");

for (const kase of CASES) {
  const collection = await db.collection.findFirstOrThrow({ where: { name: kase.collection } });
  const { chunks } = await retrieve(
    { collectionId: collection.id, question: kase.question, topK: 6 },
    deps,
  );

  const sources: AttributionSource[] = chunks.map((chunk, index) => ({
    n: index + 1,
    chunkId: chunk.chunkId,
    displayText: chunk.displayText,
  }));

  // A sentence long enough to carry evidence; the first is often a heading line.
  const longest = (text: string) =>
    splitSentences(text)
      .map((s) => s.text.trim())
      .sort((a, b) => b.length - a.length)[0] ?? text;

  const selections: [string, string][] = [
    ["verbatim", longest(sources[0].displayText)],
    ["reworded", kase.reworded],
    ["synthesis", kase.synthesis],
    ["unsupported", kase.unsupported],
  ];

  console.log(`\n${kase.question}`);
  for (const [kind, selection] of selections) {
    // The raw best score, not the post-threshold one: a calibration that only saw
    // scores which already passed the floor could not tell a near-miss from a
    // total miss, and that distinction is what the floor is being set on.
    const raw = rankPassages(selection, sources)[0]?.score ?? 0;
    const result = attribute(selection, sources);
    record(kind, raw);
    console.log(
      `  ${kind.padEnd(12)} ${raw.toFixed(3)}  ${band(raw).padEnd(9)} ` +
        `${result ? `n=${result.n} ${result.confidence}` : "no passage offered"}`,
    );
  }
}

console.log("\nkind           min     max    verdict");
for (const [kind, scores] of bands) {
  const min = Math.min(...scores);
  const max = Math.max(...scores);
  console.log(`${kind.padEnd(12)}  ${min.toFixed(3)}   ${max.toFixed(3)}   ${band(min)}..${band(max)}`);
}

const reworded = bands.get("reworded") ?? [];
const synthesis = bands.get("synthesis") ?? [];
const overlap = Math.min(...reworded) <= Math.max(...synthesis) && Math.min(...synthesis) <= Math.max(...reworded);
console.log(
  `\nreworded vs synthesis: ${overlap ? "OVERLAP — not separable, as ADR-0024 records" : "SEPARABLE — ADR-0024 needs revisiting"}`,
);

await db.$disconnect();
